@ECHO OFF
CLS
TYPE \SETUP\MKCLOGO.LGO
ECHO.
ECHO.
ECHO                               [44;1;5;31m MKC-SETUP-PROGRAMM [0m
ECHO                                   [40;1;36m
ECHO                            1 = Minimalkonfiguration
ECHO                            2 = Normalkonfiguration
ECHO                            3 = Norton 4.0 startet durch
ECHO                            4 = Windows startet durch
ECHO                            5 = Komplette Konfiguration[0m
C:\SETUP\AUTOSET.EXE
