'DECLARE SUB SavePicture (Datei$, PicBeginX%, PicBeginY%, PicEndX%, PicEndY%)
'SUB SavePicture (Datei$, PicBeginX%, PicBeginY%, PicEndX%, PicEndY%)

'---- Hier beginnt SAVEPICTURE ----------
CLOSE #1

OPEN Datei$ FOR RANDOM AS #1 LEN = 16
FIELD #1, 8 AS c$, 8 AS c2$


ID$ = "MKC-PIC"
VID$ = "Ver. 1.0"
LSET c$ = ID$
LSET c2$ = VID$
PUT #1, 1


LSET c$ = MKI$(PicBeginX%)
PUT #1, 2
LSET c$ = MKI$(PicEndX%)
PUT #1, 3
LSET c$ = MKI$(PicBeginY%)
PUT #1, 4
LSET c$ = MKI$(PicEndY%)
PUT #1, 5

x% = PicBeginX%
y% = PicBeginY%
Dat% = 6

FOR i = 1 TO (PicEndY% - PicBeginY%)
 FOR j = 1 TO ((PicEndX% - PicBeginX%) / 2)

 col% = POINT(x%, y%)
 PSET (x%, y%), col% - 1

 LSET c$ = MKD$(col%)
 PUT #1, Dat%
 
 x% = x% + 1
 IF x% = PicEndX% THEN EXIT FOR

 col% = POINT(x%, y%)
 PSET (x%, y%), col% - 1

 LSET c2$ = MKD$(col%)
 PUT #1, Dat%

 Dat% = Dat% + 1
 x% = x% + 1

 NEXT j

y% = y% + 1
x% = PicBeginX%
NEXT i

SOUND 3000, 1
'---- Hier endet SAVEPICTURE ----------

'*****************************************************************************
'*****************************************************************************

'DECLARE SUB ViewPicture (Datei$, XPos%, YPos%)
'SUB ViewPicture (Datei$, XPos%, YPos%)

'---- Hier beginnt VIEWPICTURE ---------
CLOSE #1

 OPEN Datei$ FOR RANDOM AS #1 LEN = 16
 FIELD #1, 8 AS c$, 8 AS c2$

GET #1, 2
PicBeginX% = CVI(c$)
GET #1, 3
PicEndX% = CVI(c$)
PicEndX% = PicEndX% + XPos%
GET #1, 4
PicBeginY% = CVI(c$)
GET #1, 5
PicEndY% = CVI(c$)
PicEndY% = PicEndY% + YPos%

Dat% = 6
x% = XPos%
y% = YPos%

FOR i = 1 TO (PicEndY% - YPos% - PicBeginY%)
 FOR j = 1 TO (((PicEndX% - XPos%) - PicBeginX%) / 2)

 GET #1, Dat%
 d# = CVD(c$)
 PSET (x%, y%), d#

 x% = x% + 1
 IF x% = PicEndX% - PicBeginX% THEN EXIT FOR

 GET #1, Dat%
 d# = CVD(c2$)
 PSET (x%, y%), d#

 Dat% = Dat% + 1
 x% = x% + 1

 NEXT j

y% = y% + 1
x% = XPos%
NEXT i
'---- Hier endet VIEWPICTURE ----------
