BackDoor - Gotta get away !

I suppose we chose BackDoor because we brainstormed our brain and the storm
whistled BackDoor.
What I wanna say is that there's nothing to say!

Got it ?! Get lost! 

You are still here? Damned! OK, so y'll be 'onored:

The BackDoor facts:    (taataaaaa...!)
-------------------

...BD is Captain Olliwood (uks, uks, uks, ...)
...and ouwso (=also) the Chip-sy-King 

GREAT FACTS! AIN'T THA' ?

OK, thats 'ly all!
GO HOME (scrawnk your chick!)






















Still here? Get lost now. Screw ya'self! Got it?

OK...more facts!

Today, 25th February '95 (I guess), 00:21, We're listening to the greatest
band since the summer of '69 : Offspring !

